from datetime import datetime
from typing import Protocol

from ticket_triage_llm.schemas.trace import TraceRecord


class TraceRepository(Protocol):
    def save_trace(self, trace: TraceRecord) -> None: ...

    def get_traces_by_run(self, run_id: str) -> list[TraceRecord]: ...

    def get_traces_by_provider(self, provider: str) -> list[TraceRecord]: ...

    def get_traces_since(self, since: datetime) -> list[TraceRecord]: ...

    def get_recent_traces(self, limit: int) -> list[TraceRecord]: ...

    def get_all_traces(self) -> list[TraceRecord]: ...
